name: deploy-pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust
    steps:
      - name: Prepare
        run: |
          #apk update
          #apk add rustup
          #apk add bash git tar
          #apk add clang20 clang20-libclang wasi-compiler-rt
          #rustup-init -y -t wasm32-unknown-unknown --default-toolchain beta
          # apk add rust cargo wasm-pack
          #apk add wasm-pack
          #source ~/.cargo/env
          apt update
          apt install -y clang libclang-rt-dev-wasm32
          cargo +beta install wasm-pack
          clang --version
          cargo +beta --version
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: cargo +beta xtask pack
      - name: Deploy
        run: cargo +beta xtask deploy
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: DEMO
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
